config/routes.rb
Rails.application.routes.draw do
  root to: "events#index"
  get '/events', to: 'events#index', defaults: { format: 'json' } #この行を追記
  # get '/events/new' => "events#new"
  # post '/events' => "events#create"
  get '/events/list' => 'events#list'
  # get '/events/:id/edit' => 'events#edit'
  # patch '/events/:id' => 'events#update'
  resources :events, only: %i[new create edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    respond_to do |format|
      format.html
      format.json { render 'calendar' }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to "/"
  end

  def list
    @events = Event.all
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to events_list_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :start, :end)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>イベントを編集できるよ！</h1>

<div>
  <%= form_with model: @event, url: event_path do |f| %>
    <div>
      <%= f.label "タイトル" %>
      <%= f.text_field :title, autofocus: true %>
    </div>
    <div>
      <%= f.label "開始日" %>
      <%= f.text_field :start %>
    </div>
    <div>
      <%= f.label "終了日" %>
      <%= f.text_field :end %>
    </div>
    <%= f.submit "保存する" %>
  <% end %>
</div>

app/views/events/index.html.erb
<div id="calendar" class="main_calendar"></div>

app/views/events/list.html.erb
<h1>予定一覧</h1>

<div>
  <table class="table content_list">
    <tr>
      <thead>
        <th>番号</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th></th>
      </thead>
    </tr>
    <% @events.each do |event| %>
      <tr>
        <tbody>
          <td><%= event.id %></td>
          <td><%= event.title %></td>
          <td><%= event.start %></td>
          <td><%= event.end %></td>
          <td><%= link_to "編集する", "/events/#{event.id}/edit" %></td>
        </tbody>
      </tr>
    <% end %>
  </table>
</div>

app/views/events/new.html.erb
<h1>イベントの投稿をする</h1>

<div>
  <%= form_with model: @event do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true %>
    </div>
    <div>
      <%= f.label "開始日" %>
      <%= f.text_field :start, id: "start_datepicker", placeholder: "カレンダーを表示" %>
    </div>
    <div>
      <%= f.label "終了日" %>
      <%= f.text_field :end, id: "end_datepicker", placeholder: "カレンダーを表示" %>
    </div>
    <div>
      <%= f.submit "保存する" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="logo">
        <ul>
          <li><%= link_to("カレンダー", "/") %></li>
          <li><%= link_to "新たな予定", new_event_path %></li>
          <li><%= link_to "予定リスト", events_list_path %></li>
        </ul>
      </div>
    </header>
    <main class="main_content">
      <%= yield %>
    </main>
  </body>
</html>